### ISSUE TITLE
replicant error

### ISSUE THREAD

**Issue by listepo** [HyperDex/homebrew-hyperdex#5]
air-ivan:~ ivan$ brew install hyperdex
==> Installing hyperdex dependency: replicant
==> Downloading http://hyperdex.org/src/replicant-0.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/replicant-0.4.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/replicant/0.4.0
==> make
# define HASH_FUN_H <tr1/functional>

```
               ^
```

1 error generated.
make[1]: **\* [daemon/failure_manager.o] Error 1
make: **\* [all] Error 2

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/hyperdex/homebrew-hyperdex/issues

**Comment by rjnn** [comment]
I can confirm I am also getting this error on a fresh OS X Mavericks install on a Macbook Air, with a clean homebrew with a completely clean "brew doctor".

**Comment by dilap** [comment]
FYI: https://twitter.com/HyperDexTeam/status/462559846680641536

**Comment by rescrv** [comment]
I believe this is fixed in the latest release.  Please reopen if necessary.
