### ISSUE TITLE
1.4.0 make error

### ISSUE THREAD

**Issue by PierreRochard** [HyperDex/homebrew-hyperdex#8]
1.3.0 was building without error, and googling around didn't turn anything up.
Here is the error message:

<pre>
HyperDex Rochard$ brew install hyperdex --with-python-bindings
==> Downloading http://hyperdex.org/src/hyperdex-1.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/hyperdex-1.4.0.tar.gz
==> Patching
patching file cityhash/city.cc
Hunk #1 succeeded at 501 (offset 2 lines).
==> ./configure --prefix=/usr/local/Cellar/hyperdex/1.4.0 --enable-python-bindings
==> make
ao_hash_map<K, V, H, EMPTY> :: resize_table(bucket** table,
                               ^~~~~~~~~~~~
1 error generated.
make[1]: *** [daemon/hyperdex_daemon-datalayer_checkpointer_thread.o] Error 1
make: *** [all] Error 2
</pre>

Please let me know if there's any additional information I can provide.

Thank you!

**Comment by DylanGriffith** [comment]
I am having a similar problem. Did you end up solving this?

**Comment by PierreRochard** [comment]
Hi @DylanGriffith, I have not resolved it yet, @rescrv is looking into it.

**Comment by cwilkes** [comment]
Here's the error I'm getting (not doing --with-python-bindings for now):

$ brew install hyperdex
==> Downloading http://hyperdex.org/src/hyperdex-1.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/hyperdex-1.4.0.tar.gz
==> Patching
patching file cityhash/city.cc
Hunk #1 succeeded at 501 (offset 2 lines).
==> ./configure --prefix=/usr/local/Cellar/hyperdex/1.4.0
==> make
make[1]: **\* [daemon/hyperdex_daemon-datalayer_encodings.o] Error 1
make[1]: **\* [daemon/hyperdex_daemon-datalayer_checkpointer_thread.o] Error 1
1 error generated.
make[1]: **\* [daemon/hyperdex_daemon-datalayer.o] Error 1
make: **\* [all] Error 2

brew info hyperdex shows that the recipe came from https://github.com/hyperdex/homebrew-hyperdex/blob/master/hyperdex.rb

**Comment by rescrv** [comment]
Fixed in 1.4.2 (announcement pending).
